services:
  - name: portfolio-laravel
    type: web
    runtime: docker
    plan: free
    repo: https://github.com/deepmonapara9/portfolio-laravel
    region: oregon
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host
      - key: DB_DATABASE
        value: your-db-name
      - key: DB_USERNAME
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password
    buildCommand: |
      docker build -t portfolio-laravel .
    startCommand: docker run -p 8000:8000 portfolio-laravel
